server:
  port: 9528
mybatis-plus:
  type-aliases-package: com.smart.mall.dto
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
spring:
  application:
    name: service-zuul-gateway
  zipkin:
    base-url: http://127.0.0.1:9411/
    sleuth:
      sampler:
        probability: 1
  boot:
    admin:
      client:
        url: http://localhost:9011
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB03?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 520WANGjian
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      cache-state: true
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://service-registry-7001.com:7001/eureka/,http://service-registry-7002.com:7002/eureka/,http://service-registry-7003.com:7003/eureka/
  instance:
    instance-id: gateway-9528.com  #要做域名映射  在host 127.0.0.1 gateway-9527.com
    prefer-ip-address: true

zuul:
  ignored-services: "*" #不能直接访问真实名字
  prefix: /wj #加访问前缀
  routes:
    api-a:
      serviceId: smart-mall-service-provider-demo #把该名字映射为mydept
      path: /api1/**
    api-b:
      serviceId: service-zuul-gateway
      path: /api2/**
    api-c:
      serviceId: MICROSERVICECLOUD-PURCHASE
      path: /api3/**
  FormBodyWrapperFilter:
    pre:
      disable: false
info:
  app.name: wj-micservicecloud
  company.name: www.wj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
swagger:
  enable: true
