spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  d-name: dev
  profiles: dev
  application:
    name: smart-mall-service-provider-demo
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB03?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 520WANGjian
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  zipkin:
    base-url: http://127.0.0.1:9411/
    sleuth:
      sampler:
        probability: 1
  boot:
    admin:
      client:
        url: http://localhost:9011
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  security:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: service-provider-8001
    prefer-ip-address: true
info:
  app.name: wj-microservicecloud
  company.name: www.wj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring:
  d-name: prod
  profiles: prod
  application:
    name: smart-mall-service-provider-demo
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 520WANGjian
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  zipkin:
    base-url: http://127.0.0.1:9411/
    sleuth:
      sampler:
        probability: 1
  boot:
    admin:
      client:
        url: http://localhost:9011
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  security:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: service-provider-8001
    prefer-ip-address: true
info:
  app.name: wj-microservicecloud
  company.name: www.wj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
