server:
  port: 7002
spring:
  application:
    name: service-registry-7002
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1
  boot:
    admin:
      client:
        url: http://localhost:9011
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    hostname: service-registry-7002.com #eureka服务端的实例名称
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://service-registry-7001.com:7001/eureka/,http://service-registry-7003.com:7003/eureka/