server:
  port: 9528
mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml
#  type-aliases-package: org.wj.springcloud.dto
#  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: micservicecloud-zuul-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB03?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 520WANGjian

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9528.com  #要做域名映射  在host 127.0.0.1 gateway-9527.com
    prefer-ip-address: true

zuul:
  ignored-services: "*" #不能直接访问真实名字
  prefix: /wj #加访问前缀
  routes:
    api-a:
      serviceId: smart-mall-service-provider-demo #把该名字映射为mydept
      path: /api1/**
    api-b:
      serviceId: microservicecloud-dept2
      path: /api2/**
    api-c:
      serviceId: MICROSERVICECLOUD-PURCHASE
      path: /api3/**
  FormBodyWrapperFilter:
    pre:
      disable: false
info:
  app.name: wj-micservicecloud
  company.name: www.wj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
swagger:
  enable: true
